# GKE specific variables
prefix                    = "mholland"
project_id                = ""
region                    = "australia-southeast1"
zone                      = "australia-southeast1-a"
plus_machine_type         = "f1-micro"
nginx_machine_type        = "e2-standard-8"
nginx_controller_os_image = "projects/ubuntu-os-cloud/global/images/ubuntu-1804-bionic-v20210112"
nginx_plus_os_image       = "projects/ubuntu-os-cloud/global/images/ubuntu-1804-bionic-v20210112"
ssh_username              = "ubuntu"
ssh_pub_key_path          = "/home/APIAutopsies/terraform/ssh/id_rsa.pub"
ssh_pri_key_path          = "/home/APIAutopsies/terraform/ssh/id_rsa"
